# Site settings
title: Be a Blue
description: Buena Vista City Public Schools Be a Blue
baseurl: "http://waynegraham.github.io/beablue"
url: "http://beablue.org"

# Dependencies
markdown:     kramdown
highlighter:  rouge

# Permalinks
permalink:    pretty

sass:
  sass_dir: _sass
  style:    expanded
  deploy_style: compressed

exclude: ["Gemfile", "Procfile", "Gemfile.lock", "Gruntfile.js", "node_modules", "bower_components", "package.json", "_sass", "LICENSE", "bower.json"]

gems:
  - jekyll-sitemap
  - jekyll-sass
